(() => {
  'use strict';
  const root=document.getElementById('changelog-timeline'),indexRoot=document.getElementById('changelog-index-list');
  if(!root||!indexRoot)return;
  const INITIAL_CHANGELOG_GROUPS=8,CHANGELOG_CHUNK_SIZE=8;
  const curatedGroups=(Array.isArray(window.CHUNBONG_CHANGELOG)?window.CHUNBONG_CHANGELOG:[]).filter(group=>group&&/^20\d{2}-\d{2}-\d{2}$/.test(String(group.date||''))).map(group=>({date:group.date,items:Array.isArray(group.items)?group.items:[]})).sort((a,b)=>b.date.localeCompare(a.date));
  let groups=curatedGroups.map(group=>({date:group.date,items:[...group.items]})),renderGeneration=0,dateObserver=null;
  const checkpoint=window.CHUNBONG_CHANGELOG_META||{},autoSummarizer=window.CHUNBONG_CHANGELOG_AUTO;
  const titleKey=(value='')=>String(value).toLowerCase().replace(/\s*\(#\d+\)\s*$/,'').replace(/[^0-9a-z가-힣]+/g,'').trim();
  function mergeAutomaticGroups(automaticGroups=[]){const byDate=new Map(curatedGroups.map(group=>[group.date,{date:group.date,items:[...group.items]}])),seenByDate=new Map();for(const group of curatedGroups)seenByDate.set(group.date,new Set(group.items.map(item=>titleKey(item?.title||'')).filter(Boolean)));for(const automaticGroup of Array.isArray(automaticGroups)?automaticGroups:[]){const date=String(automaticGroup?.date||'');if(!/^20\d{2}-\d{2}-\d{2}$/.test(date))continue;if(!byDate.has(date))byDate.set(date,{date,items:[]});if(!seenByDate.has(date))seenByDate.set(date,new Set());const target=byDate.get(date),seen=seenByDate.get(date);for(const item of Array.isArray(automaticGroup?.items)?automaticGroup.items:[]){const title=String(item?.title||'').trim(),key=titleKey(title);if(!title||!key||seen.has(key))continue;seen.add(key);target.items.push({type:['new','improved','fixed'].includes(item?.type)?item.type:'improved',title,description:String(item?.description||'').trim(),auto:true})}}groups=[...byDate.values()].filter(group=>group.items.length).sort((a,b)=>b.date.localeCompare(a.date))}
  const labels={new:'신규',improved:'개선',fixed:'수정'},esc=(value='')=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const formatDate=date=>{const parsed=new Date(date+'T00:00:00+09:00');if(Number.isNaN(parsed.getTime()))return{main:date,sub:''};return{main:new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'long',day:'numeric'}).format(parsed),sub:new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',weekday:'long'}).format(parsed)}};
  function cardHtml(item){const kind=['new','improved','fixed'].includes(item?.type)?item.type:'improved',description=String(item?.description||'').trim();return '<article class="changelog-card"><div class="changelog-card-top"><span class="changelog-kind" data-kind="'+kind+'">'+labels[kind]+'</span><h3>'+esc(item?.title||'업데이트')+'</h3></div>'+(description?'<p>'+esc(description)+'</p>':'')+'</article>'}
  function groupHtml(group){const date=formatDate(group.date);return '<section class="changelog-day reveal" id="changelog-'+esc(group.date)+'" data-changelog-date="'+esc(group.date)+'"><div class="changelog-date"><time datetime="'+esc(group.date)+'">'+esc(date.main)+'</time><small>'+esc(date.sub)+' · '+group.items.length+'개</small></div><div class="changelog-entries">'+group.items.map(cardHtml).join('')+'</div></section>'}
  function setActiveDate(date){indexRoot.querySelectorAll('a').forEach(link=>{const active=link.dataset.changelogIndexDate===date;link.classList.toggle('active',active);if(active){link.setAttribute('aria-current','true');if(window.innerWidth<=760)link.scrollIntoView({block:'nearest',inline:'center'})}else link.removeAttribute('aria-current')})}
  function setupDateObserver(){dateObserver?.disconnect();if(!('IntersectionObserver'in window))return;dateObserver=new IntersectionObserver(rows=>{const visible=rows.filter(row=>row.isIntersecting).sort((a,b)=>Math.abs(a.boundingClientRect.top)-Math.abs(b.boundingClientRect.top));if(visible[0])setActiveDate(visible[0].target.dataset.changelogDate||'')},{rootMargin:'-92px 0px -62% 0px',threshold:[0,.01,.1]});root.querySelectorAll('.changelog-day').forEach(node=>dateObserver.observe(node))}
  function setupReveal(scope=root){const nodes=scope.matches?.('.reveal')?[scope]:[...scope.querySelectorAll('.reveal')];if(!('IntersectionObserver'in window)){nodes.forEach(node=>node.classList.add('visible'));return}const observer=new IntersectionObserver(rows=>rows.forEach(row=>{if(row.isIntersecting){row.target.classList.add('visible');observer.unobserve(row.target)}}),{threshold:.03});nodes.forEach(node=>observer.observe(node))}
  const scheduleIdle=fn=>window.ChunbongIdle?.schedule?window.ChunbongIdle.schedule(fn,{timeout:1800}):'requestIdleCallback'in window?requestIdleCallback(fn,{timeout:1800}):setTimeout(fn,500);
  function initialGroupCount(){const hash=decodeURIComponent(String(location.hash||''));const match=hash.match(/^#changelog-(20\d{2}-\d{2}-\d{2})$/);if(!match)return Math.min(INITIAL_CHANGELOG_GROUPS,groups.length);const index=groups.findIndex(group=>group.date===match[1]);return Math.min(groups.length,Math.max(INITIAL_CHANGELOG_GROUPS,index>=0?index+1:0))}
  function render(latestKey=''){
    const generation=++renderGeneration,total=groups.reduce((sum,group)=>sum+group.items.length,0),latest=document.getElementById('changelog-latest'),count=document.getElementById('changelog-count'),status=document.getElementById('changelog-sync-status');
    if(latest)latest.textContent=groups[0]?.date||'LATEST';if(count)count.textContent=total+'개의 주요 업데이트 · '+groups.length+'일 기록';if(status){status.textContent='사용자에게 중요한 변경사항만 한글로 간단하게 정리했습니다.';status.className='changelog-sync-status is-live'}
    indexRoot.innerHTML=groups.map(group=>'<a href="#changelog-'+esc(group.date)+'" data-changelog-index-date="'+esc(group.date)+'"><span>'+esc(group.date)+'</span><small>'+group.items.length+'</small></a>').join('');
    if(!groups.length)root.innerHTML='<div class="changelog-empty">등록된 업데이트가 없습니다.</div>';
    else{const first=initialGroupCount();root.innerHTML=groups.slice(0,first).map(groupHtml).join('');setupReveal();let cursor=first;const append=()=>{if(generation!==renderGeneration||cursor>=groups.length)return;const end=Math.min(cursor+CHANGELOG_CHUNK_SIZE,groups.length),holder=document.createElement('div');holder.innerHTML=groups.slice(cursor,end).map(groupHtml).join('');const fragment=document.createDocumentFragment();while(holder.firstChild)fragment.appendChild(holder.firstChild);const added=[...fragment.childNodes];root.appendChild(fragment);added.forEach(node=>{if(node.nodeType===1)setupReveal(node)});cursor=end;setupDateObserver();if(cursor<groups.length)scheduleIdle(append)};if(cursor<groups.length)scheduleIdle(append)}
    if(groups[0])setActiveDate(groups[0].date);setupDateObserver();const resolvedKey=latestKey||('date:'+String(groups[0]?.date||'none')+':'+total);try{localStorage.setItem('chunbong-changelog-seen-v2',resolvedKey)}catch{}document.dispatchEvent(new CustomEvent('chunbong:changelog-ready',{detail:{latestKey:resolvedKey,latestDate:groups[0]?.date||''}}));
  }
  function applyHistory(payload){const summarized=autoSummarizer?.summarizeSince?autoSummarizer.summarizeSince(payload?.groups,checkpoint):[];mergeAutomaticGroups(summarized);render(payload?.latest?.sha||payload?.latest?.shortSha||'')}
  const cachedHistory=window.ChunbongCache?.peek?.('changelog-history');if(cachedHistory)applyHistory(cachedHistory);else render();
  const CHANGELOG_SYNC_INTERVAL_MS=10*60*1000;let changelogSyncAt=0,changelogSyncPromise=null;
  function refreshAutomaticChangelog({force=false}={}){const now=Date.now();if(!force&&changelogSyncAt&&now-changelogSyncAt<CHANGELOG_SYNC_INTERVAL_MS)return changelogSyncPromise||Promise.resolve();if(changelogSyncPromise)return changelogSyncPromise;changelogSyncAt=now;changelogSyncPromise=(async()=>{try{const since=String(checkpoint.throughTime||'').trim(),historyUrl='/api/content?type=changelog-history'+(since?'&since='+encodeURIComponent(since):'');let payload;if(window.ChunbongCache)payload=await window.ChunbongCache.fetchJson('changelog-history',historyUrl,{ttl:CHANGELOG_SYNC_INTERVAL_MS,force,staleIfError:true});else{const response=await fetch(historyUrl,{headers:{accept:'application/json'}});if(!response.ok)throw new Error('changelog_history_unavailable');payload=await response.json()}applyHistory(payload)}catch{}finally{changelogSyncPromise=null}})();return changelogSyncPromise}
  void refreshAutomaticChangelog();window.addEventListener('focus',()=>{void refreshAutomaticChangelog()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')void refreshAutomaticChangelog()});
})();