(()=>{
  'use strict';
  const ROWS=10,COLS=17,GAME_MS=120000,COMBO_WINDOW=2400,BEST_KEY='chungwagame-best-v2',RANKING_ENDPOINT='/api/content?type=chungwagame-ranking&mode=classic';
  const $=id=>document.getElementById(id);const e={root:$('chungwagame'),board:$('cg-board'),wrap:$('cg-board-wrap'),dragRect:$('cg-drag'),hintRect:$('cg-hint'),fx:$('cg-fx-layer'),combo:$('cg-combo'),score:$('cg-score'),best:$('cg-best'),timer:$('cg-timer'),timeFill:$('cg-time-fill'),sum:$('cg-sum'),sumBox:$('cg-selection-box'),message:$('cg-message'),startOverlay:$('cg-start-overlay'),pauseOverlay:$('cg-pause-overlay'),overOverlay:$('cg-over-overlay'),start:$('cg-start'),resume:$('cg-resume'),again:$('cg-again'),pauseRestart:$('cg-pause-restart'),pauseRanking:$('cg-pause-ranking'),hintBtn:$('cg-hint-btn'),shuffle:$('cg-shuffle'),pause:$('cg-pause'),sound:$('cg-sound'),soundIcon:$('cg-sound-icon'),soundLabel:$('cg-sound-label'),restart:$('cg-restart'),ranking:$('cg-ranking'),rankingModal:$('cg-ranking-modal'),rankingClose:$('cg-ranking-close'),rankingStatus:$('cg-ranking-status'),rankingList:$('cg-ranking-list'),final:$('cg-final'),finalCombo:$('cg-final-combo'),finalCleared:$('cg-final-cleared'),resultMessage:$('cg-result-message')};
  if(!e.root||!e.board)return;
  let board=[],score=0,best=Number(localStorage.getItem(BEST_KEY)||0),remainingMs=GAME_MS,running=false,paused=false,endAt=0,rafId=0,drag=null,soundOn=true,audioCtx=null,combo=0,maxCombo=0,cleared=0,lastClearAt=0,hintTimer=0,modalPaused=false,modalFromPause=false;
  function setStatus(status){e.root.dataset.gameStatus=status}
  function randomValue(){const r=Math.random();if(r<.12)return 1;if(r<.25)return 2;if(r<.39)return 3;if(r<.54)return 4;if(r<.70)return 5;if(r<.82)return 6;if(r<.90)return 7;if(r<.96)return 8;return 9}
  function createBoard(){board=Array.from({length:ROWS*COLS},(_,index)=>({index,row:Math.floor(index/COLS),col:index%COLS,value:randomValue(),removed:false,el:null}));ensureMove()}
  function ensureMove(){if(findHint())return;const active=board.filter(c=>!c.removed);if(active.length>=2){active[0].value=4;active[1].value=6}}
  function renderBoard(){const frag=document.createDocumentFragment();e.board.replaceChildren();for(const cell of board){const div=document.createElement('div');div.className='cg-fruit'+(cell.removed?' empty':'');div.dataset.index=String(cell.index);div.setAttribute('role','gridcell');div.setAttribute('aria-label',cell.removed?'빈 칸':`숫자 ${cell.value}`);if(!cell.removed){const shape=document.createElement('div');shape.className='cg-fruit-shape';shape.dataset.value=String(cell.value);div.append(shape)}cell.el=div;frag.append(div)}e.board.append(frag)}
  function formatTime(ms){const sec=Math.max(0,Math.ceil(ms/1000));return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
  function updateHud(){e.score.textContent=String(score);e.best.textContent=String(best);e.timer.textContent=formatTime(remainingMs);e.timeFill.style.transform=`scaleX(${Math.max(0,Math.min(1,remainingMs/GAME_MS))})`}
  function setMessage(text){e.message.textContent=text}
  function setSelectionSum(sum){e.sum.textContent=String(sum);e.sumBox.style.background=sum===10?'#eaffad':sum>10?'#fff0e8':'#f3f7e8';e.sum.style.color=sum===10?'#78a500':sum>10?'#ef6a49':'#83af00'}
  function hideOverlays(){e.startOverlay.classList.add('hidden');e.pauseOverlay.classList.add('hidden');e.overOverlay.classList.add('hidden')}
  function snapshot(){return{score,maxCombo,cleared,remainingMs,status:e.root.dataset.gameStatus||'start'}}
  function startGame(){cancelAnimationFrame(rafId);clearHint();clearDrag();createBoard();score=0;remainingMs=GAME_MS;combo=0;maxCombo=0;cleared=0;lastClearAt=0;running=true;paused=false;endAt=performance.now()+remainingMs;renderBoard();updateHud();setSelectionSum(0);setMessage('합이 10이 되도록 드래그하세요!');hideOverlays();setStatus('playing');tick();sound.start()}
  function tick(now=performance.now()){if(!running||paused)return;remainingMs=Math.max(0,endAt-now);updateHud();if(remainingMs<=0){endGame();return}rafId=requestAnimationFrame(tick)}
  function endGame(){if(!running)return;remainingMs=0;running=false;paused=false;cancelAnimationFrame(rafId);clearDrag();clearHint();try{localStorage.setItem(BEST_KEY,String(best))}catch{}updateHud();e.final.textContent=String(score);e.finalCombo.textContent=`x${Math.max(1,maxCombo)}`;e.finalCleared.textContent=String(cleared);e.resultMessage.textContent=score>=120?'춘과 마스터! 완벽해요 🍇':score>=70?'콤보 감각이 정말 좋아요!':score>=35?'좋아요! 다음 판은 더 높게!':'10 조합이 보이기 시작했어요!';e.overOverlay.classList.remove('hidden');setStatus('gameover');sound.finish()}
  function pauseGame(showOverlay=true){if(!running||paused)return false;remainingMs=Math.max(0,endAt-performance.now());paused=true;cancelAnimationFrame(rafId);setStatus('paused');clearDrag();if(showOverlay)e.pauseOverlay.classList.remove('hidden');setMessage('게임이 잠시 멈췄어요.');return true}
  function resumeGame(){if(!running||!paused)return false;paused=false;e.pauseOverlay.classList.add('hidden');endAt=performance.now()+remainingMs;setStatus('playing');setMessage('다시 시작! 합이 10인 조합을 찾아보세요.');tick();sound.ui();return true}
  function getCellFromPoint(x,y){const r=e.board.getBoundingClientRect();if(x<r.left||x>r.right||y<r.top||y>r.bottom)return null;const px=Math.min(r.width-.01,Math.max(0,x-r.left)),py=Math.min(r.height-.01,Math.max(0,y-r.top));return{col:Math.min(COLS-1,Math.floor(px/r.width*COLS)),row:Math.min(ROWS-1,Math.floor(py/r.height*ROWS))}}
  const bounds=(a,b)=>({r1:Math.min(a.row,b.row),r2:Math.max(a.row,b.row),c1:Math.min(a.col,b.col),c2:Math.max(a.col,b.col)});
  function cellsInBounds(b){const cells=[];for(let r=b.r1;r<=b.r2;r++)for(let c=b.c1;c<=b.c2;c++){const cell=board[r*COLS+c];if(!cell.removed)cells.push(cell)}return cells}
  function drawRect(el,b){const br=e.board.getBoundingClientRect(),wr=e.wrap.getBoundingClientRect(),cw=br.width/COLS,ch=br.height/ROWS;Object.assign(el.style,{display:'block',left:`${br.left-wr.left+b.c1*cw}px`,top:`${br.top-wr.top+b.r1*ch}px`,width:`${(b.c2-b.c1+1)*cw}px`,height:`${(b.r2-b.r1+1)*ch}px`})}
  function updateDrag(x,y){if(!drag)return;const cell=getCellFromPoint(x,y);if(!cell)return;drag.end=cell;const b=bounds(drag.start,drag.end);drag.bounds=b;const cells=cellsInBounds(b),selected=new Set(cells.map(c=>c.index)),sum=cells.reduce((t,c)=>t+c.value,0);for(const c of board)c.el?.classList.toggle('selected',selected.has(c.index));setSelectionSum(sum);drawRect(e.dragRect,b);e.dragRect.classList.toggle('valid',sum===10&&cells.length>0);setMessage(sum===10?`딱 10! 손을 놓으면 ${cells.length}개가 팡!`:sum>10?`합계 ${sum} · 10을 넘었어요!`:`합계 ${sum} · ${10-sum}만 더!`)}
  function finishDrag(){if(!drag)return;const b=drag.bounds||bounds(drag.start,drag.start),cells=cellsInBounds(b),sum=cells.reduce((t,c)=>t+c.value,0);if(sum===10&&cells.length)clearCells(cells,b);else{sound.miss();setMessage(sum?`합계 ${sum} · 10이 아니에요.`:'빈 칸이에요. 다른 곳을 골라보세요.')}clearDrag()}
  function clearDrag(){drag=null;e.dragRect.style.display='none';e.dragRect.classList.remove('valid');for(const c of board)c.el?.classList.remove('selected');setSelectionSum(0)}
  function clearCells(cells,b){const now=performance.now();combo=now-lastClearAt<=COMBO_WINDOW?combo+1:1;lastClearAt=now;maxCombo=Math.max(maxCombo,combo);const gain=cells.length*combo;score+=gain;cleared+=cells.length;if(score>best)best=score;for(const cell of cells){cell.removed=true;cell.el?.classList.add('good')}updateHud();setMessage(combo>=2?`${cells.length}개 팡! +${gain}점 · COMBO x${combo}`:`${cells.length}개 팡! +${gain}점`);showSuccessEffect(b,gain);if(combo>=2)showCombo(combo);sound.clear(combo);setTimeout(()=>{for(const cell of cells){if(cell.el){cell.el.classList.remove('good');cell.el.classList.add('empty');cell.el.replaceChildren()}}if(!findHint()&&board.some(c=>!c.removed))setMessage('가능한 10 조합이 없어요. 섞기를 눌러보세요!')},360)}
  function showSuccessEffect(b,gain){const br=e.board.getBoundingClientRect(),wr=e.wrap.getBoundingClientRect(),cw=br.width/COLS,ch=br.height/ROWS,x=br.left-wr.left+(b.c1+b.c2+1)*cw/2,y=br.top-wr.top+(b.r1+b.r2+1)*ch/2;for(let i=0;i<12;i++){const p=document.createElement('i');p.className='cg-burst';p.style.left=`${x}px`;p.style.top=`${y}px`;const angle=(Math.PI*2*i)/12,dist=34+Math.random()*46;p.style.setProperty('--dx',`${Math.cos(angle)*dist}px`);p.style.setProperty('--dy',`${Math.sin(angle)*dist}px`);e.fx.append(p);setTimeout(()=>p.remove(),650)}const pop=document.createElement('b');pop.className='cg-score-pop';pop.textContent=`+${gain}`;pop.style.left=`${x}px`;pop.style.top=`${y}px`;e.fx.append(pop);setTimeout(()=>pop.remove(),760)}
  function showCombo(n){e.combo.textContent=`COMBO x${n}`;e.combo.classList.remove('show');void e.combo.offsetWidth;e.combo.classList.add('show')}
  function findHint(){for(let r1=0;r1<ROWS;r1++)for(let c1=0;c1<COLS;c1++){if(board[r1*COLS+c1].removed)continue;for(let r2=r1;r2<Math.min(ROWS,r1+5);r2++)for(let c2=c1;c2<Math.min(COLS,c1+6);c2++){const b={r1,r2,c1,c2},cells=cellsInBounds(b);if(cells.length&&cells.reduce((t,c)=>t+c.value,0)===10)return b}}return null}
  function showHint(){if(!running||paused)return;clearHint();const h=findHint();if(!h){setMessage('지금은 10 조합이 안 보여요. 섞어보세요!');sound.miss();return}drawRect(e.hintRect,h);setMessage('점선 안 숫자의 합이 10이에요!');sound.hint();hintTimer=setTimeout(clearHint,2200)}
  function clearHint(){clearTimeout(hintTimer);hintTimer=0;e.hintRect.style.display='none'}
  function shuffleBoard(){if(!running||paused)return;clearHint();const active=board.filter(c=>!c.removed),values=active.map(c=>c.value);for(let i=values.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]]}active.forEach((c,i)=>c.value=values[i]);ensureMove();renderBoard();setMessage('남은 춘과를 섞었어요!');sound.shuffle()}
  function pointerDown(ev){if(!running||paused)return;const cell=getCellFromPoint(ev.clientX,ev.clientY);if(!cell)return;ev.preventDefault();e.wrap.setPointerCapture?.(ev.pointerId);drag={start:cell,end:cell,bounds:bounds(cell,cell)};updateDrag(ev.clientX,ev.clientY)}
  function pointerMove(ev){if(!drag)return;ev.preventDefault();updateDrag(ev.clientX,ev.clientY)}function pointerUp(ev){if(!drag)return;ev.preventDefault();finishDrag()}
  function getAudio(){if(!soundOn)return null;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;if(!audioCtx)audioCtx=new AC();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
  function tone(freq,duration=.08,type='sine',volume=.025,delay=0){const ctx=getAudio();if(!ctx)return;const osc=ctx.createOscillator(),gain=ctx.createGain(),t=ctx.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(freq,t);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(volume,t+.008);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(gain);gain.connect(ctx.destination);osc.start(t);osc.stop(t+duration+.03)}
  const sound={ui(){tone(659,.055,'sine',.018);tone(988,.07,'triangle',.012,.035)},start(){tone(523,.08,'sine',.024);tone(659,.09,'triangle',.018,.055);tone(784,.11,'sine',.018,.11)},clear(n=1){const base=[659,784,988,1175,1319][Math.min(n-1,4)];tone(base,.075,'sine',.026);tone(base*1.25,.095,'triangle',.018,.045);if(n>=2)tone(base*1.5,.1,'sine',.014,.09)},hint(){tone(988,.06,'sine',.018);tone(1319,.08,'triangle',.015,.055)},shuffle(){tone(523,.05,'triangle',.015);tone(659,.05,'triangle',.015,.045);tone(784,.07,'triangle',.015,.09)},miss(){tone(294,.055,'sine',.012);tone(247,.07,'sine',.009,.04)},finish(){[659,784,988,1319].forEach((f,i)=>tone(f,.14,'sine',.02,i*.075))}};
  function toggleSound(){soundOn=!soundOn;e.sound.setAttribute('aria-pressed',String(soundOn));e.soundIcon.textContent=soundOn?'🔊':'🔇';e.soundLabel.textContent=soundOn?'ON':'OFF';if(soundOn)sound.ui()}
  async function loadRanking(){e.rankingStatus.textContent='랭킹 불러오는 중…';try{const response=await fetch(RANKING_ENDPOINT,{headers:{accept:'application/json'}});if(!response.ok)throw new Error('ranking');const payload=await response.json();renderRanking(payload.entries||[]);e.rankingStatus.textContent=payload.entries?.length?'현재 TOP 10':'아직 등록된 기록이 없어요.';return payload.entries||[]}catch{e.rankingStatus.textContent='랭킹을 불러오지 못했습니다.';return[]}}
  function renderRanking(entries=[]){const frag=document.createDocumentFragment();entries.slice(0,10).forEach((entry,index)=>{const li=document.createElement('li'),rank=document.createElement('span'),name=document.createElement('strong'),metric=document.createElement('span');rank.textContent=String(entry.rank??index+1);name.textContent=String(entry.nickname??'-');metric.textContent=`${Number(entry.score)||0} · x${Number(entry.maxCombo)||1}`;li.append(rank,name,metric);frag.append(li)});e.rankingList.replaceChildren(frag)}
  function openRanking(){modalPaused=running&&!paused;modalFromPause=running&&paused;if(modalPaused)pauseGame(false);e.pauseOverlay.classList.add('hidden');e.rankingModal.hidden=false;void loadRanking();e.rankingClose.focus?.()}
  function closeRanking(){if(e.rankingModal.hidden)return;e.rankingModal.hidden=true;if(modalPaused&&running&&paused)resumeGame();else if(modalFromPause&&running&&paused)e.pauseOverlay.classList.remove('hidden');modalPaused=false;modalFromPause=false}
  function handleEscape(ev){if(ev.key!=='Escape')return;if(!e.rankingModal.hidden){ev.preventDefault();closeRanking();return}if(!running)return;ev.preventDefault();paused?resumeGame():pauseGame(true)}
  e.start.addEventListener('click',startGame);e.again.addEventListener('click',startGame);e.resume.addEventListener('click',resumeGame);e.pauseRestart.addEventListener('click',startGame);e.pauseRanking.addEventListener('click',openRanking);e.hintBtn.addEventListener('click',showHint);e.shuffle.addEventListener('click',shuffleBoard);e.pause.addEventListener('click',()=>paused?resumeGame():pauseGame(true));e.sound.addEventListener('click',toggleSound);e.restart.addEventListener('click',startGame);e.ranking.addEventListener('click',openRanking);e.rankingClose.addEventListener('click',closeRanking);e.rankingModal.querySelector('[data-cg-ranking-close]')?.addEventListener('click',closeRanking);e.wrap.addEventListener('pointerdown',pointerDown);e.wrap.addEventListener('pointermove',pointerMove);e.wrap.addEventListener('pointerup',pointerUp);e.wrap.addEventListener('pointercancel',clearDrag);document.addEventListener('keydown',handleEscape);window.addEventListener('resize',()=>{if(drag?.bounds)drawRect(e.dragRect,drag.bounds)});
  createBoard();renderBoard();updateHud();void loadRanking();
  globalThis.ChungwagameApp=Object.freeze({getSnapshot:snapshot,startGame,pauseGame,resumeGame,setGameOver:endGame,loadRanking,renderRanking});
})();