(()=>{
'use strict';
if(document.body?.dataset?.page==='operator')return;
if(!document.querySelector('link[data-feedback-styles]')){const l=document.createElement('link');l.rel='stylesheet';l.href='feedback-widget.css';l.dataset.feedbackStyles='';document.head.append(l)}
const fab=document.createElement('button');fab.type='button';fab.className='feedback-fab';fab.dataset.feedbackOpen='';fab.textContent='건의 · 피드백';document.body.append(fab);
const dialog=document.createElement('div');dialog.className='feedback-dialog';dialog.hidden=true;dialog.innerHTML=`<section class="feedback-card" role="dialog" aria-modal="true" aria-labelledby="feedback-title"><header><div><small>CHUNBONG FAN HUB</small><h2 id="feedback-title">건의 · 피드백</h2></div><button class="feedback-close" type="button" aria-label="닫기">×</button></header><form id="feedback-form"><div class="feedback-field"><label for="feedback-category">어떤 의견인가요?</label><select id="feedback-category"><option value="bug">버그 신고</option><option value="inconvenience">불편한 점</option><option value="feature">기능 제안</option><option value="design">디자인 의견</option><option value="content">콘텐츠 요청</option><option value="other">기타</option></select></div><div class="feedback-field"><label for="feedback-nickname">닉네임 (선택)</label><input id="feedback-nickname" maxlength="24" autocomplete="nickname" placeholder="비워두면 익명"><small>선택사항이에요. 입력하지 않으면 익명으로 전달됩니다.</small></div><div class="feedback-field"><label for="feedback-message">내용</label><textarea id="feedback-message" maxlength="2000" required placeholder="불편했던 점이나 원하는 기능을 편하게 적어주세요."></textarea></div><p class="feedback-privacy-note">현재 페이지·기기 유형·화면 크기·PWA 여부·테마가 함께 전달됩니다. 원본 IP 주소는 피드백 내용에 저장하지 않습니다.</p><button class="feedback-submit" type="submit">피드백 보내기</button><p class="feedback-status" aria-live="polite"></p></form><div class="feedback-success" hidden><strong>전송되었습니다 ✓</strong><p>의견 감사합니다. 피드백 번호 <b></b></p><button class="feedback-submit" type="button" data-feedback-done>닫기</button></div></section>`;document.body.append(dialog);
const form=dialog.querySelector('#feedback-form'),status=dialog.querySelector('.feedback-status'),success=dialog.querySelector('.feedback-success');
const visitor=()=>{try{return localStorage.getItem('chunbong:analytics:visitor:v1')||''}catch{return''}};
const device=()=>Math.min(innerWidth,screen.width||innerWidth)<=760?'mobile':Math.min(innerWidth,screen.width||innerWidth)<=1100?'tablet':'desktop';
function open(){dialog.hidden=false;document.body.classList.add('feedback-open');document.body.style.overflow='hidden';form.hidden=false;success.hidden=true;setTimeout(()=>dialog.querySelector('#feedback-message')?.focus(),30)}
function close(){dialog.hidden=true;document.body.classList.remove('feedback-open');document.body.style.overflow='';status.textContent=''}
document.addEventListener('click',e=>{if(e.target.closest('[data-feedback-open]')){e.preventDefault();open()}});
dialog.querySelector('.feedback-close').addEventListener('click',close);dialog.querySelector('[data-feedback-done]').addEventListener('click',close);dialog.addEventListener('click',e=>{if(e.target===dialog)close()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dialog.hidden)close()});
form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('.feedback-submit');button.disabled=true;status.textContent='전송 중…';try{const payload={category:dialog.querySelector('#feedback-category').value,nickname:dialog.querySelector('#feedback-nickname').value,message:dialog.querySelector('#feedback-message').value,page:location.pathname,visitorId:visitor(),device:device(),viewport:innerWidth+'x'+innerHeight,pwa:matchMedia('(display-mode: standalone)').matches||navigator.standalone===true,theme:document.documentElement.dataset.theme==='light'?'light':'dark'};const r=await fetch('/api/content?type=feedback-submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error||'submit_failed');form.reset();form.hidden=true;success.hidden=false;success.querySelector('b').textContent=data.id||'';window.ChunbongAnalytics?.track?.('feedback_submit')}catch(err){status.textContent=err.message==='rate_limited'?'잠시 후 다시 보내주세요.':'전송하지 못했습니다. 잠시 후 다시 시도해 주세요.'}finally{button.disabled=false}});
})();