import fs from 'node:fs';
import assert from 'node:assert/strict';

const html=fs.readFileSync(new URL('../chungwagame.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../chungwagame.css',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../chungwagame.js',import.meta.url),'utf8');
const postgame=fs.readFileSync(new URL('../chungwagame-postgame-ranking.js',import.meta.url),'utf8');

assert.match(html,/assets\/chungwagame\/mascot-header\.webp/,'header mascot image missing');
assert.match(html,/assets\/chungwagame\/mascot-ten\.webp/,'instruction 10 mascot image missing');
assert.match(css,/assets\/chungwagame\/numbers\.webp/,'number sprite missing');
assert.match(css,/saturate\(\.82\)/,'eye-comfort sprite saturation guard missing');
assert.match(css,/#080a08/i,'dark game page background missing');
assert.match(css,/background-size:5\.8823529% 100%,100% 10%/,'regular board grid lines missing');
assert.match(css,/Grid readability pass: 2026-09-20/,'grid readability override missing');
assert.match(css,/rgba\(226,228,221,\.16\)/,'regular cell grid must remain clearly visible');
assert.match(css,/regular cells only, no 5-cell helper grid/,'grid tuning must explicitly stay single-scale');
assert.match(css,/#DDDAD2/i,'comfortable off-white board surface missing');
assert.match(css,/#F2421B/i,'requested red-orange number color missing');
assert.match(css,/content:attr\(data-value\)/,'number overlay must render from each fruit data value');
assert.match(css,/Visual discrimination pass: 2026-09-20/,'visual discrimination override missing');
for(const value of ['1','2','3','4','5','6','7','8','9'])assert.match(css,new RegExp(`\\.cg-fruit-shape\\[data-value="${value}"\\]\\{--cg-value-accent:`),`missing unique value accent ${value}`);
assert.match(css,/\.cg-drag::after\{[\s\S]*content:"합계 " attr\(data-sum\) " \/ 10"/,'floating drag sum label missing');
assert.match(css,/\.cg-drag\.over/,'over-10 visual state missing');
assert.match(js,/e\.dragRect\.dataset\.sum=String\(sum\)/,'drag sum dataset missing');
assert.match(js,/dataset\.state=state/,'drag semantic state missing');
assert.match(css,/grid-template-columns:150px minmax\(0,760px\) 104px/,'compact desktop layout missing');
assert.match(css,/max-height:calc\(100svh - 205px\)/,'short viewport board guard missing');
assert.match(html,/id="cg-time-fill"/,'time gauge missing');
assert.match(html,/id="cg-pause-restart"/,'pause restart action missing');
assert.match(html,/id="cg-pause-overlay"[\s\S]*?href="minigames\.html"[\s\S]*?미니게임으로 돌아가기/,'pause minigames return action missing');
assert.match(html,/id="cg-over-overlay"[\s\S]*?href="minigames\.html"[\s\S]*?미니게임으로 돌아가기/,'gameover minigames return action missing');
assert.match(html,/id="cg-ranking-register"/,'postgame ranking register missing');
assert.match(html,/id="cg-ranking-modal"/,'ranking modal missing');
assert.match(js,/COMBO_WINDOW=2400/,'combo window missing');
assert.match(js,/cells\.length\*combo/,'combo scoring missing');
assert.match(js,/showSuccessEffect/,'success burst effect missing');
assert.match(js,/cg-score-pop/,'success score popup missing');
assert.match(js,/e\.timeFill\.style\.transform/,'time gauge update missing');
assert.match(js,/function pauseGame\(showOverlay=true\)/,'pause state missing');
assert.match(js,/const sound=\{ui\(\)/,'fresh WebAudio sound set missing');
assert.match(js,/ChungwagameApp/,'game public app missing');
assert.match(postgame,/submitTerminalRanking/,'postgame ranking submission missing');
assert.match(postgame,/\/api\/content\?type=chungwagame-ranking/,'ranking endpoint missing');

const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size,ids.length,'duplicate IDs found');
for(const id of ['chungwagame','cg-board','cg-start','cg-pause','cg-ranking','cg-time-fill','cg-ranking-register','cg-ranking-nickname'])assert.ok(ids.includes(id),`missing ${id}`);
console.log('Chungwagame compact/effects regression passed');
